version: "3"

services:
  nub-api:
    image: fwoelffel/nub-api:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - '5432:5432'