version: "3.4"
services:

  nub-api:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '3000:3000'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - '5432:5432'

  db-admin:
    image: sosedoff/pgweb
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db?sslmode=disable
    ports:
      - '8081:8081'